ingress: https://arbeid.dev.nav.no/arbeid/dagpenger/mine-dagpenger
basePath: /arbeid/dagpenger/mine-dagpenger
dekorator:
  url: https://dekoratoren.dev.nav.no/
  env: dev
loginserviceUrl: https://loginservice.dev.nav.no/login
veilarbproxyUrl: http://veilarbproxy.q1.svc.nais.local/veilarbregistrering/


