ingress: https://arbeid.dev.nav.no/arbeid/dagpenger/mine-dagpenger
basePath: /arbeid/dagpenger/mine-dagpenger
dekorator:
  url: https://dekoratoren.dev.nav.no/
  env: dev
loginservice:
  url: https://loginservice.dev.nav.no/login
veilarbproxyUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering
amplitude:
  apiKey: 2f190e67f31d7e4719c5ff048ad3d3e6
saf:
  cluster: dev-fss
  ingress: https://safselvbetjening-q1.dev-fss-pub.nais.io
  scope: safselvbetjening-q1
personopplysningerApiUrl: https://www.dev.nav.no/person/personopplysninger-api
