ingress: https://dp-dagpenger.dev.nav.no
dekorator:
  url: https://dekoratoren.dev.nav.no/
  env: dev
loginserviceUrl: https://loginservice.dev.nav.no/login
veilarbproxyUrl: https://veilarbproxy-q1.dev.nav.no/veilarbregistrering/
