ingress: https://dp-dagpenger.dev.intern.nav.no
websocketUrl: wss://dp-dagpenger.dev.intern.nav.no/api/ws
dekoratorUrl: https://dekoratoren.dev.nav.no/
loginserviceUrl: https://loginservice.dev.nav.no/login
