ingress: https://arbeid.dev.nav.no/arbeid/dagpenger/mine-dagpenger
basePath: /arbeid/dagpenger/mine-dagpenger
dekorator:
  url: https://dekoratoren.dev.nav.no/
  env: dev
loginserviceUrl: https://loginservice.dev.nav.no/login
veilarbproxyUrl: https://veilarbproxy-q1.dev.nav.no/veilarbregistrering/


