ingress: https://arbeid.dev.nav.no/arbeid/dagpenger/mine-dagpenger
basePath: /arbeid/dagpenger/mine-dagpenger
dekorator:
  url: https://dekoratoren.dev.nav.no/
  env: dev
loginserviceUrl: https://loginservice.dev.nav.no/login
veilarbproxyUrl: https://veilarbproxy-q1.dev.nav.no/veilarbregistrering/
amplitude:
  apiKey: 2f190e67f31d7e4719c5ff048ad3d3e6
saf:
  cluster: dev-fss
  ingress: https://safselvbetjening.dev-fss-pub.nais.io
personopplysningerApiUrl: https://www.dev.nav.no/person/personopplysninger-api