apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-dagpenger"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "{{basePath}}/api/isalive"
    initialDelay: 3
  readiness:
    path: "{{basePath}}/api/isready"
    initialDelay: 3
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  env:
    - name: SELF_URL
      value: {{ingress}}
    - name: DEKORATOR_URL
      value: {{dekorator.url}}
    - name: DEKORATOR_ENV
      value: {{dekorator.env}}
    - name: REDIS_HOST
      value: dp-dagpenger-redis
    - name: REDIS_PORT
      value: "6379"
    - name: LOGINSERVICE_URL
      value: {{loginserviceUrl}}
    - name: VEILARBPROXY_URL
      value: {{veilarbproxyUrl}}
    - name: AMPLITUDE_API_KEY
      value: {{amplitude.apiKey}}
    - name: SAF_SELVBETJENING_INGRESS
      value: {{saf.ingress}}
    - name: SAF_SELVBETJENING_CLUSTER
      value: {{saf.cluster}}
    - name: PERSONOPPLYSNINGER_API_URL
      value: {{personopplysningerApiUrl}}
  envFrom:
    - secret: dp-dagpenger-redis-secret
  ingresses:
    - {{ingress}}
  accessPolicy:
    outbound:
      external:
        - host: {{saf.ingress}}
      rules:
        - application: dp-innsyn
        - application: dp-dagpenger-redis
        - application: safselvbetjening
          namespace: teamdokumenthandtering
          cluster: {{saf.cluster}}
  idporten:
    enabled: true
    redirectPath: /api/auth/callback
    frontchannelLogoutPath: /api/auth/signout
  tokenx:
    enabled: true
