ingress: https://www.nav.no/arbeid/dagpenger/mine-dagpenger
basePath: /arbeid/dagpenger/mine-dagpenger
dekorator:
  url: https://www.nav.no/dekoratoren
  env: prod
loginservice:
  url: https://loginservice.nav.no/login
veilarbproxyUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering
amplitude:
  apiKey: b0bccdd4dd75081606ef7bcab668a7ed
saf:
  cluster: prod-fss
  ingress: https://safselvbetjening.prod-fss-pub.nais.io
  scope: safselvbetjening
personopplysningerApiUrl: https://www.nav.no/person/personopplysninger-api
