ingress: https://dp-dagpenger.intern.nav.no
dekorator:
  url: https://www.nav.no/dekoratoren
  env: prod
loginserviceUrl: https://loginservice.nav.no/login
veilarbproxyUrl: https://veilarbproxy-q1.dev.nav.no/veilarbregistrering/
