ingress: https://www.nav.no/dagpenger/mine-dagpenger
dekorator:
  url: https://www.nav.no/dekoratoren
  env: prod
loginserviceUrl: https://loginservice.nav.no/login
veilarbproxyUrl: http://veilarbproxy.default.svc.nais.local
