ingress: https://www.nav.no/arbeid/dagpenger/mine-dagpenger
basePath: /arbeid/dagpenger/mine-dagpenger
dekorator:
  url: https://www.nav.no/dekoratoren
  env: prod
loginserviceUrl: https://loginservice.nav.no/login
veilarbproxyUrl: https://veilarbproxy.nais.oera.no/veilarbregistrering/
