ingress: https://www.nav.no/arbeid/dagpenger/mine-dagpenger
basePath: /arbeid/dagpenger/mine-dagpenger
dekorator:
  url: https://www.nav.no/dekoratoren
  env: prod
loginservice:
  url: https://loginservice.nav.no/login
  wellKnown: https://navnob2c.b2clogin.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
veilarbproxyUrl: https://veilarbproxy.nais.oera.no/veilarbregistrering/
amplitude:
  apiKey: b0bccdd4dd75081606ef7bcab668a7ed
saf:
  cluster: prod-fss
  ingress: https://safselvbetjening.prod-fss-pub.nais.io
personopplysningerApiUrl: https://www.nav.no/person/personopplysninger-api
