ingress: https://www.nav.no/arbeid/dagpenger/mine-dagpenger
basePath: /arbeid/dagpenger/mine-dagpenger
dekorator:
  url: https://www.nav.no/dekoratoren
  env: prod
loginservice:
  url: https://loginservice.nav.no/login
veilarbproxyUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering
amplitude:
  apiKey: 913768927b84cde5eac0d0d18c737561
saf:
  cluster: prod-fss
  ingress: https://safselvbetjening.prod-fss-pub.nais.io
  scope: safselvbetjening
personopplysningerApiUrl: https://www.nav.no/person/personopplysninger-api
soknadsdialog:
  ingress: https://www.nav.no/dagpenger/soknad/
