---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-dagpenger-redis"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
  annotations:
    nais.io/run-as-group: "0"
    nais.io/read-only-file-system: "false"
spec:
  image: bitnami/redis:6.0.12
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  accessPolicy:
    inbound:
      rules:
        - application: dp-dagpenger-redisexporter
        - application: dp-dagpenger
  envFrom:
    - secret: dp-dagpenger-redis-secret
---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-dagpenger-redisexporter"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
spec:
  image: oliver006/redis_exporter:v1.17.0-alpine
  port: 9121
  prometheus:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  liveness:
    path: /health
  accessPolicy:
    outbound:
      rules:
        - application: dp-dagpenger-redis
  env:
    - name: REDIS_ADDR
      value: dp-dagpenger-redis:6379
    - name: REDIS_EXPORTER_LOG_FORMAT
      value: json
  envFrom:
    - secret: dp-dagpenger-redis-secret
