name: Build and deploy

on: [push]

env:
  IMAGE: ghcr.io/${{ github.repository }}/dp-dagpenger:${{ github.sha }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"

      - run: npm install --no-save --no-audit --prefer-offline
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - run: npm test

  build:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Package Repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up .npmrc to use in Docker build
        uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"

      - run: cp $NPM_CONFIG_USERCONFIG .npmrc

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ env.IMAGE }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}"

      - name: Archive NAIS yaml
        uses: actions/upload-artifact@v3
        with:
          name: nais-yaml
          path: .nais

  upload-cdn:
    needs: [test, build]
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/cache@v3
        with:
          path: ./.next/static
          key: ${{ github.sha }}
          fail-on-cache-miss: true

      - name: Upload static files
        uses: navikt/frontend/actions/cdn-upload/v1@main
        with:
          cdn-team-name: teamdagpenger
          source: ./.next/static
          destination: "/dp-dagpenger/_next"

  deploy-dev:
    needs: [test, build, upload-cdn]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch NAIS yaml
        uses: actions/download-artifact@v3
        with:
          name: nais-yaml
          path: .nais

      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/dev.yaml
          PRINT_PAYLOAD: true

  deploy-prod:
    needs: [test, build, upload-cdn]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch NAIS yaml
        uses: actions/download-artifact@v1
        with:
          name: nais-yaml
          path: .nais

      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/prod.yaml
          PRINT_PAYLOAD: true
